- pom.xml
> Warning about https://github.com/jenkinsci/plugin-pom/pull/36

- src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
- src/test/java/io/blueocean/rest/pipeline/editor/PipelineMetadataServiceTest.java
[JENKINS-40240](https://issues.jenkins-ci.org/browse/JENKINS-40240)
cc @reviewbybees esp @michaelneale @i386 @kzantow
> [FIXED JENKINS-40240] Add .../wrapperMetadata endpoint

- pom.xml
> Update to Declarative 0.7 release

- pom.xml
- src/main/java/io/blueocean/rest/pipeline/editor/ExportedBuildCondition.java
- src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
[JENKINS-40239](https://issues.jenkins-ci.org/browse/JENKINS-40239)
Other side of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/76
cc @reviewbybees esp @kzantow
> [FIXED JENKINS-40239] Add build condition descriptions to metadata

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
- src/main/js/components/EditorDemo.jsx
- src/main/js/components/editor/AddStepSelectionDialog.jsx
- src/main/js/components/editor/EditorMain.jsx
- src/main/js/components/editor/EditorPage.jsx
- src/main/js/components/editor/EditorPipelineGraph.jsx
- src/main/js/components/editor/EditorStepDetails.jsx
- src/main/js/components/editor/common.jsx
- src/main/js/components/editor/steps/BatScriptStepEditor.jsx
- src/main/js/components/editor/steps/BuildStepEditor.jsx
- src/main/js/components/editor/steps/EchoStepEditor.jsx
- src/main/js/components/editor/steps/GenericStepEditor.jsx
- src/main/js/components/editor/steps/properties/BooleanPropertyInput.jsx
- src/main/js/components/editor/steps/properties/DecimalPropertyInput.jsx
- src/main/js/components/editor/steps/properties/IntegerPropertyInput.jsx
- src/main/js/components/editor/steps/properties/StringPropertyInput.jsx
- src/main/js/services/PipelineStore.js
- src/main/js/services/PipelineSyntaxConverter.js
- src/main/less/editor.less
- src/test/js/StepMetadata.json
- src/test/js/services/PipelineModelExamples.groovy
- src/test/js/services/PipelineSyntaxConverter-spec.js
This provides bidirectional import/export for Pipeline Model Definition for the graphical editor.
See it in action:
[![See it in action](https://img.youtube.com/vi/6z3tgfNyWXk/0.jpg)](https://www.youtube.com/watch?v=6z3tgfNyWXk)
> [FIX JENKINS-39372] enable bidirectional import/export for Pipeline Model Definition

- src/main/js/components/editor/AgentConfiguration.jsx
- src/main/js/components/editor/EditorMain.jsx
- src/main/js/components/editor/EditorPage.jsx
- src/main/js/components/editor/EnvironmentConfiguration.jsx
- src/main/less/editor.less
> Better styling for config panel

- src/main/java/io/blueocean/rest/pipeline/editor/PipelineMetadataService.java
- src/main/js/services/PipelineSyntaxConverter.js
- src/main/js/services/fetchClassic.js
> [FIX JENKINS-41387] Work with and without crumbs enabled

- src/main/js/components/editor/AddStepSelectionSheet.jsx
> JENKINS-41360 - sort step selections

- pom.xml
- src/main/js/components/editor/EditorPage.jsx
- src/main/resources/index.jelly
> Prepare for preview release

- pom.xml
- src/main/js/components/EditorPreview.jsx
- src/main/js/components/editor/EditorPage.jsx
- src/main/js/services/PipelineSyntaxConverter.js
- src/main/less/editor.less
- src/test/js/services/PipelineSyntaxConverter-spec.js
'Unknown' sections not handled by the editor are captured and restored, but this was happening at the branch level, not the top-level stage level.
This is the only pertinent commit: https://github.com/jenkinsci/blueocean-pipeline-editor-plugin/pull/28/commits/c51c716adab83fa36cf19593f317f972581f6f77
> Stage sections not properly captured

- src/main/js/components/properties/DecimalPropertyInput.jsx
- src/main/js/components/properties/IntegerPropertyInput.jsx
I think parsing the value from the input will fix the issue of having the value serialized as a string instead of a Integer or a decimal
> JENKINS-42640: Fix parsing int and float parameter values

- src/main/js/EditorPage.jsx
- src/main/js/jenkins-js-extension.yaml
- src/main/js/services/PipelineValidator.js
- src/main/less/editor.less
Add handlers to notify the user if they will lose changes in the editor by navigating away.
> [FIX JENKINS-42650] - notify when leaving pipeline page

- src/main/js/components/editor/EditorPipelineGraph.jsx
- src/main/less/editor.less
> [FIX JENKINS-41611] Update node designs

- src/main/js/components/properties/DecimalPropertyInput.jsx
- src/main/js/components/properties/IntegerPropertyInput.jsx
- src/main/less/header-buttons.less
Issue with spacing of numeric inputs.
... erhm accidentally pushed a fix for a style issue affecting params:
> [FIX JENKINS-42598] - spacing issue with numeric inputs

- src/main/js/EditorPage.jsx
- src/main/js/SaveApi.js
Depends on https://github.com/jenkinsci/blueocean-plugin/pull/920 for branch saving to work properly.
> [FIX JENKINS-43014] GitHub save from branch

- src/main/js/components/editor/EditorPipelineGraph.jsx
- src/main/js/services/fetchClassic.js
- src/main/less/editor.less
An issue prevented some AJAX calls to work on EDGE and the node styles were quite bad. Tested now across Chrome, Firefox, Safari, EDGE. Also cleaned up a few code issues.
> [FIX JENKINS-42982] - fix issue on EDGE & node styles

- src/main/js/components/properties/IntegerPropertyInput.jsx
Correcting BigInteger dataType.
> Fix BigInteger data type (was BigInterger)

- README.md
Ping @kzantow @cliffmeyers for sanity check / anything you want me to add.
> Small update to README with run instructions

- src/main/js/EditorPage.jsx
- src/main/js/PipelineEditorLink.jsx
MBP functionality can be tested with bitbucket create pipeline and using branch from https://github.com/jenkinsci/blueocean-plugin/pull/1292.
See [JENKINS-45922](https://issues.jenkins-ci.org/browse/JENKINS-45922).
> JENKINS-45922# MBP indexing and Jenkinsfile edit/save support

- src/main/js/PipelineEditorLink.jsx
This PR adds a tool-tip text for the edit action icon
See [JENKINS-45192](https://issues.jenkins-ci.org/browse/JENKINS-45192).
> add title text to the edit icon

- src/main/js/EditorPage.jsx
- src/main/js/SaveApi.js
- Fixes bug where Editor dialog page shows title as 'reponame/undefined' for multi-branch pipeline with empty repo. Fix is to show 'reponame'. 
- Transition to activity page after receiving MBP indexing sse completion event with a timeout
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
> Fix mbp emptyrepo name

- package.json
- pom.xml
- src/main/js/PipelineEditorLink.jsx
- src/main/js/components/MoreMenu.jsx
- src/main/js/components/Sheets.jsx
- src/main/js/components/editor/AddStepSelectionSheet.jsx
- src/main/js/components/editor/EditorMain.jsx
- src/main/js/components/editor/EditorStepList.jsx
Related to https://github.com/jenkinsci/blueocean-plugin/pull/1306
See [JENKINS-45743](https://issues.jenkins-ci.org/browse/JENKINS-45743).
> remove react-material-icons dep, use the ones from the JDL

- README.md
- src/main/js/EditorPage.jsx
- src/main/js/SaveApi.js
Reverts jenkinsci/blueocean-pipeline-editor-plugin#53
> Revert "github/ghe indexing"
